services:
  financialqabot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financialqa-container
    ports:
      - 80:8501
    volumes:
      - .:/app
      - ./cache:/app/cache
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    tty: true
    restart: always